### ISSUE TITLE
TODO: CSS - Layout

### ISSUE THREAD

**Issue by natpoulson** [natpoulson/developer-portfolio#3]
Before delving into the weeds too much, it's important to establish the layout of the elements.

Based on the mock up:

- [x] Container for body and header content will need to be centered with white space on either side.
  - [x] At a minimum there must be room for the navigation menu to breathe.
- [x] The content sections are stacked vertically, with their contents arranged horizontally.
- [x] The first project in the projects section has to be larger than the others.
- [x] Breakpoints for the most common screen dimensions should be accounted for, collapsing into reduced or single column layouts accordingly
