### ISSUE TITLE
TODO: README content, preview, repo cleanup, and publish

### ISSUE THREAD

**Issue by natpoulson** [natpoulson/developer-portfolio#7]
- [x] Populate README with content
  - [x] Capture and attach screenshot of the site for the README
- [x] Generate and attach MIT license to repo
- [x] Ensure all issues before this one have been completed
- [x] Deploy the page to GitHub Pages
